global:
  projectName: free5gc
  userPlaneArchitecture: single

  # Storage class for MongoDB PV
  storageClass: local-path

  amf:
    service:
      ngap:
        enabled: true
        name: amf-n2
        port: 38412
        protocol: SCTP
        type: LoadBalancer
        
  # N2 network (AMF <-> gNB NGAP)
  n2network:
    enabled: true
    name: n2network
    type: ipvlan
    masterIf: enp1s0
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254

  # N3 network (UPF <-> gNB GTP-U)
  n3network:
    enabled: true
    name: n3network
    type: ipvlan
    masterIf: enp1s0
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238

  # N4 network (UPF <-> SMF PFCP)
  n4network:
    enabled: true
    name: n4network
    type: ipvlan
    masterIf: enp1s0
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246

  # N6 network (UPF <-> Data Network)
  n6network:
    enabled: true
    name: n6network
    type: ipvlan
    masterIf: enp1s0
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
    excludeIP: 10.100.100.254

  # N9 network (UPF <-> UPF, inter-UPF)
  n9network:
    enabled: true
    name: n9network
    type: ipvlan
    masterIf: enp1s0
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230

free5gc-upf:
  upf:
    n3if:
      ipAddress: 10.100.50.233
    n4if:
      ipAddress: 10.100.50.241
    n6if:
      ipAddress: 10.100.100.12
    n9if:
      ipAddress: 10.100.50.225

free5gc-amf:
  amf:
    n2if:
      ipAddress: 10.100.50.249

free5gc-smf:
  smf:
    n4if:
      ipAddress: 10.100.50.242
